###############################################################################
#
#                        Travis CI configuration
#                        =======================
#
# This file configures the Continuous Integration server on travis-ci.org
#
###############################################################################

language: python

# This will route the build job to the new Travis build environment
sudo: false

# Keep installed lilypond versions between builds
cache:
  directories:
  - $HOME/.lilypond

install:
# Download and install LilyPond (stable and devel)
# when not present already (cached between builds)
  - python ./test/install_lilypond.py
# Download script to install fonts
# (this is currently not cached)
  - git clone https://github.com/openlilylib/lily-fonts.git $HOME/.lily-fonts

script:
# download and install alternative notation fonts
  - python $HOME/.lily-fonts/install-lily-fonts --batch --init --font-directory $HOME/.fonts --targets $HOME/.lilypond/lilypond
# run the tests
  - ./test/automated_tests.py

# These are environment variables that are used to configure the
# tests.
#
#   - LILY_PLATFORM is the platform for which lilypond was
#                   compiled. Note that travis-ci is running 64 bit
#                   Linux virtual machines, hence `linux-64` is pretty
#                   much the only value that makes sense.
#
#   - LILY_VERSION is the version of lilypond with which we want to
#                  run the tests. "stable" and "devel" are placeholders
#                  for values retrieved from test/LILYPOND-VERSIONS
#                  during the installation and test scripts
env:
  - LILY_PLATFORM=linux-64 LILY_VERSION=2.18.2-1
  - LILY_PLATFORM=linux-64 LILY_VERSION=2.19.17-1
